name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: beta-bot
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r bot/requirements-dev.txt
          pip install -e .
      - name: Run pytest
        run: pytest

  web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
